include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - 'lib/**.g.dart'
    - 'lib/**.freezed.dart'
    - 'lib/injections.config.dart'
linter:
  rules:
    public_member_api_docs: false
