name: flutterissuesapp
description: A Flutter App to see and filter github flutter issues.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0
  dartz: ^0.10.0-nullsafety.2
  envify: ^2.0.0
  flutter_bloc: ^7.0.0
  flutter_markdown: ^0.6.2
  freezed_annotation: ^0.14.2
  get_it: ^7.1.3
  github_api_repository:
    path: ./packages/github_api_repository
  google_fonts: ^2.1.0
  graphql_flutter: ^5.0.0-nullsafety.2
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  hive_repository:
    path: ./packages/hive_repository
  injectable: ^1.4.0
  intl: ^0.17.0
  json_annotation: ^4.0.1
  jiffy: ^4.1.0
  pedantic: ^1.11.0
  routemaster: ^0.7.2
  rxdart: ^0.26.0
  url_launcher: ^6.0.3

dev_dependencies:
  build_runner:
  bloc_test: ^8.0.0
  envify_generator: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  freezed: ^0.14.2
  injectable_generator: ^1.4.0
  integration_test:
    sdk: flutter
  json_serializable: ^4.1.1
  mocktail: ^0.1.2
  very_good_analysis: ^2.0.3

## When on stable channel, uncomment this
## to avoir dependencies incompatibilities
# dependency_overrides:
#  crypto: ^3.0.0
#  convert: ^3.0.0
#  args: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
