
name: flutterissuesapp-dev

on:
   push :
        branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0

      - name: Create env file
        env:
            SECRET_FILE: ${{ secrets.ENVS }}
        run: echo "$SECRET_FILE" | base64 --decode > .env

      #Inside package Helper_repository
      - name: Install dependencies
        working-directory: ./packages/helper_repository
        run: flutter packages get
      - name: format
        working-directory: ./packages/helper_repository
        run: flutter format --set-exit-if-changed lib test
      - name: Analyze
        working-directory: ./packages/helper_repository
        run: flutter analyze lib test
      - name: Run tests
        working-directory: ./packages/helper_repository
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random

      # Inside package Hive repository
      - name: Install dependencies
        working-directory: ./packages/hive_repository
        run: flutter packages get
      - name: format
        working-directory: ./packages/hive_repository
        run: flutter format --set-exit-if-changed lib test
      - name: Run build_runner
        working-directory: ./packages/hive_repository
        run: |
            flutter pub run build_runner build --delete-conflicting-outputs
      - name: Analyze
        working-directory: ./packages/hive_repository
        run: flutter analyze lib test
      - name: Run tests
        working-directory: ./packages/hive_repository
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: flutter format --set-exit-if-changed lib test

      - name: Analyze
        run: flutter analyze lib test

      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          exclude: "lib/**.freezed.dart lib/**.g.dart"
          path: "./coverage/lcov.info"
          min_coverage: 10
