
name: flutterissuesapp-dev

on:
   push :
        branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0

      - name: Create env file
        env:
            SECRET_FILE: ${{ secrets.ENVS }}
        run: echo "$SECRET_FILE" | base64 --decode > .env
      - name: Create google-services.json file for android
        env:
            GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
        run: echo "$GOOGLE_SERVICES" | base64 --decode > android/app/google-services.json

      - name: Switch to flutter channel bet
        run: flutter channel beta
      #Inside package Helper_repository
      - name: Install dependencies Helper Repository
        working-directory: ./packages/helper_repository
        run: flutter packages get
      - name: format
        working-directory: ./packages/helper_repository
        run: flutter format --set-exit-if-changed lib test
      - name: Analyze
        working-directory: ./packages/helper_repository
        run: flutter analyze lib test
      - name: Run tests
        working-directory: ./packages/helper_repository
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random

      # Inside package Hive repository
      - name: Install dependencies Hive Repository
        working-directory: ./packages/hive_repository
        run: flutter packages get
      - name: format
        working-directory: ./packages/hive_repository
        run: flutter format --set-exit-if-changed lib test
      - name: Run build_runner
        working-directory: ./packages/hive_repository
        run: |
            flutter pub run build_runner build --delete-conflicting-outputs
      - name: Analyze
        working-directory: ./packages/hive_repository
        run: flutter analyze lib test
      - name: Run tests
        working-directory: ./packages/hive_repository
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random

      # Inside package Github repository
      - name: Install dependencies Github repository
        working-directory: ./packages/github_api_repository
        run: flutter packages get
      - name: format
        working-directory: ./packages/hive_repository
        run: flutter format --set-exit-if-changed lib test
      - name: Run build_runner
        working-directory: ./packages/github_api_repository
        run: |
            flutter pub run build_runner build --delete-conflicting-outputs
      - name: Analyze
        working-directory: ./packages/github_api_repository
        run: flutter analyze lib test
      - name: Run tests
        working-directory: ./packages/github_api_repository
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random

      - name: Install Dependencies root
        run: flutter packages get
      - name: Run build_runner
        run: |
            flutter pub run build_runner build --delete-conflicting-outputs

      - name: Format
        run: flutter format --set-exit-if-changed lib test

      - name: Analyze
        run: flutter analyze lib test

      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          exclude: "lib/**.freezed.dart lib/**.g.dart"
          path: "./coverage/lcov.info"
          min_coverage: 10


     # ## Add when stable channel support null safety test_driver
     # ## Or use beta channel but assembleAndroidTest is failing
     # - name: Generating assembleAndroidTest and assembleDebug
     #   env:
     #       KEYSTOREFILE: ${{ secrets.KEYSTORE }}
     #       FLUTTERISSUESAPP_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD : ${{ secrets.FLUTTERISSUESAPP_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD }}
     #      FLUTTERISSUESAPP_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.FLUTTERISSUESAPP_ANDROID_KEYSTORE_PASSWORD }}
     #      FLUTTERISSUESAPP_ANDROID_KEYSTORE_ALIAS: ${{ secrets.FLUTTERISSUESAPP_ANDROID_KEYSTORE_ALIAS }}
     #  run: |
     #      mkdir ~/keystores
     #      echo "$KEYSTOREFILE" | base64 --decode > ~/keystores/flutterissuesapp-key.keystore
     #      pushd android
     #      flutter build apk --flavor production -t lib/main_production.dart
     #      gradle app:assembleAndroidTest
     #      gradle app:assembleDebug -Ptarget=integration_test/app_test.dart
     #      popd
     #- name: Run tests on Firebase Test Lab
     #  uses: asadmansr/Firebase-Test-Lab-Action@v1.0
     #  with:
     #    arg-spec: 'tests.yaml:android-pixel-4'
     #  env:
     #    SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT_KEY }}
