

name: flutterissuesapp-test

on:
   push :
        branches: [gh]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0

      - name: Create env file
        env:
            SECRET_FILE: ${{ secrets.ENVS }}
        run: echo "$SECRET_FILE" | base64 --decode > .env
      - name: Create google-services.json file for android
        env:
            GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
        run: echo "$GOOGLE_SERVICES" | base64 --decode > android/app/google-services.json

      #Inside package Helper_repository
      - name: Install dependencies Helper Repository
        working-directory: ./packages/helper_repository
        run: flutter packages get

      # Inside package Hive repository
      - name: Install dependencies Hive Repository
        working-directory: ./packages/hive_repository
        run: flutter packages get
      - name: Run build_runner
        working-directory: ./packages/hive_repository
        run: |
            flutter pub run build_runner build --delete-conflicting-outputs

      # Inside package Github repository
      - name: Install dependencies Github repository
        working-directory: ./packages/github_api_repository
        run: flutter packages get
      - name: Run build_runner
        working-directory: ./packages/github_api_repository
        run: |
            flutter pub run build_runner build --delete-conflicting-outputs

      - name: Install Dependencies root
        run: flutter packages get
      - name: Run build_runner
        run: |
            flutter pub run build_runner build --delete-conflicting-outputs

      - name: Adding keystore and envs then build appbundle
        env:
            KEYSTOREFILE: ${{ secrets.KEYSTORE }}
            FLUTTERISSUESAPP_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD : ${{ secrets.FLUTTERISSUESAPP_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD }}
            FLUTTERISSUESAPP_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.FLUTTERISSUESAPP_ANDROID_KEYSTORE_PASSWORD }}
            FLUTTERISSUESAPP_ANDROID_KEYSTORE_ALIAS: ${{ secrets.FLUTTERISSUESAPP_ANDROID_KEYSTORE_ALIAS }}
        run: |
            mkdir ~/keystores
            echo "$KEYSTOREFILE" | base64 --decode > ~/keystores/flutterissuesapp-key.keystore
            flutter build appbundle --flavor production -t lib/main_production.dart -v

      # ## To add when integration test implemented
     # - name: Run tests on Firebase Test Lab
     #   uses: asadmansr/Firebase-Test-Lab-Action@v1.0
     #   with:
     #     arg-spec: 'tests.yaml:android-pixel-4'
     #   env:
     #     SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT_KEY }}
