

name: flutterissuesapp-test

on:
   push :
        branches: [gh]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0

      - name: Create env file
        env:
            SECRET_FILE: ${{ secrets.ENVS }}
        run: echo "$SECRET_FILE" | base64 --decode > .env
      - name: Create google-services.json file for android
        env:
            GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
        run: echo "$GOOGLE_SERVICES" | base64 --decode > android/app/google-services.json

      - name: Adding keystore and envs
        env:
            KEYSTOREFILE: ${{ secrets.KEYSTORE }}
            PRIVATE_KEY_PASSWORD: ${{ secrets.FLUTTERISSUESAPP_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD }}
            KEYSTORE_PASSWORD: ${{ secrets.FLUTTERISSUESAPP_ANDROID_KEYSTORE_PASSWORD }}
            ALIAS: ${{ secrets.FLUTTERISSUESAPP_ANDROID_KEYSTORE_ALIAS }}
        run: |
            mkdir ~/keystores
            echo "KEYSTOREFILE" | base64 --decode > ~/keystores/flutterissuesapp-key.keystore


      - name: Install Dependencies root
        run: flutter packages get
      - name: Run build_runner
        run: |
            flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build the app
        run: flutter build apk --flavor production -t lib/main_production.dart

      - name: Run tests on Firebase Test Lab
        uses: asadmansr/Firebase-Test-Lab-Action@v1.0
        with:
          arg-spec: 'testLab.yaml:android-pixel-4'
        env:
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT_KEY }}
